//! Access to the third-party dependency manifest that `build.rs` embeds into
//! the binaries at compile time.
//!
//! The build script writes three files into `OUT_DIR`:
//!
//! * `third_party_licenses.json`      — uncompressed structured data; the
//!   release workflow copies this straight into the archive as
//!   `THIRD-PARTY-LICENSES.json`. Not embedded in the binary (~3 MB).
//! * `third_party_licenses.json.gz`   — zlib-compressed JSON; embedded here
//!   via `include_bytes!` and decompressed on demand by [`load`]. Keeps
//!   binary growth on the order of a few hundred KB.
//! * `third_party_licenses.txt`       — pre-rendered plain text, shipped as
//!   `THIRD-PARTY-LICENSES.txt` in the release archive. The runtime does not
//!   embed this; `super::render::render_all` can regenerate byte-identical
//!   output from a loaded [`Manifest`] whenever `gix licenses --all` or
//!   `ein licenses --all` is invoked.

use std::io;

use super::types::Manifest;

/// Zlib-compressed JSON manifest, embedded at compile time.
pub const JSON_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/third_party_licenses.json.gz"));

/// Decompress the embedded JSON into an owned UTF-8 string.
///
/// This is exposed so the `licenses --format json` subcommand can stream the
/// manifest verbatim without re-serialising a parsed `Manifest`.
pub fn json() -> io::Result<String> {
    let bytes = miniz_oxide::inflate::decompress_to_vec_zlib(JSON_GZ)
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, format!("inflate failed: {e:?}")))?;
    String::from_utf8(bytes).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("embedded manifest is not valid UTF-8: {e}"),
        )
    })
}

/// Parse the embedded manifest into a [`Manifest`].
///
/// Errors here are treated as fatal by the subcommands — they indicate a
/// build-script/runtime schema drift or a corrupted embedded blob, neither
/// of which the CLI can recover from usefully.
pub fn load() -> io::Result<Manifest> {
    let json_str = json()?;
    serde_json::from_str(&json_str).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("failed to parse embedded license manifest: {e}"),
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_blob_decompresses_to_utf8_json() {
        let text = json().expect("decompression and utf-8 check must succeed");
        assert!(!text.is_empty(), "decompressed JSON must be non-empty");
        assert!(
            text.trim_start().starts_with('{'),
            "decompressed output should be a JSON object"
        );
    }

    #[test]
    fn embedded_manifest_round_trips_through_serde() {
        let manifest = load().expect("embedded manifest must round-trip through serde");
        // Either the real manifest (many crates) or a stub (zero crates,
        // generated_at starting with "stub;"). Both are acceptable; anything
        // that fails to deserialise is not.
        assert!(!manifest.target_triple.is_empty() || manifest.generated_at.starts_with("stub"));
    }

    #[test]
    fn runtime_render_matches_archive_txt_byte_for_byte() {
        // The `THIRD-PARTY-LICENSES.txt` in release archives is generated by
        // `build.rs` via `render_all`. The binary regenerates the same bytes
        // at runtime from the embedded JSON via the very same function — so
        // `gix licenses --all` output must equal the archive file verbatim.
        let manifest = load().expect("load manifest");
        let mut rendered = Vec::new();
        super::super::render::render_all(&mut rendered, &manifest).expect("render_all");

        let txt_from_out_dir = std::fs::read(concat!(env!("OUT_DIR"), "/third_party_licenses.txt"))
            .expect("archive .txt must exist in OUT_DIR");

        assert_eq!(
            rendered,
            txt_from_out_dir,
            "runtime rendering drifted from build-time rendering (byte counts: runtime={}, build={})",
            rendered.len(),
            txt_from_out_dir.len(),
        );
    }

    /// Every crate the embedded manifest surfaces must be coverable by
    /// `deny.toml`'s `[licenses] allow = [...]` list.
    ///
    /// This mirrors cargo-deny's semantics: a crate passes when at least one
    /// SPDX identifier in its expression is in the allowlist for `OR` unions,
    /// and every identifier is in the allowlist for `AND` conjunctions. Our
    /// SPDX parser is slightly different from cargo-deny's, which makes this
    /// a useful belt-and-suspenders check for drift.
    ///
    /// We approximate the per-crate rule as "the intersection of this crate's
    /// parsed SPDX ids with the allowlist must be non-empty"; a full
    /// boolean-expression evaluator would be more faithful but would require
    /// reproducing cargo-deny's SPDX parser here, which is overkill.
    #[test]
    fn every_crate_is_coverable_by_deny_toml_allowlist() {
        use std::collections::BTreeSet;
        use std::path::Path;

        let manifest = load().expect("load manifest");
        let deny_path = Path::new(env!("CARGO_MANIFEST_DIR")).join("deny.toml");
        let deny_content = std::fs::read_to_string(&deny_path).expect("read deny.toml");
        let allow: BTreeSet<String> = parse_deny_allow_list(&deny_content);
        assert!(
            !allow.is_empty(),
            "parse_deny_allow_list returned no SPDX ids — the parser broke, not the data"
        );

        let mut unsatisfied: Vec<(String, String, Vec<String>)> = Vec::new();
        for c in &manifest.crates {
            let Some(expr) = c.spdx.as_deref() else {
                continue;
            };
            let ids = super::super::build_support::parse_spdx_ids(expr);
            let intersection: Vec<String> = ids.iter().filter(|id| allow.contains(*id)).cloned().collect();
            if intersection.is_empty() {
                unsatisfied.push((c.name.clone(), c.version.clone(), ids));
            }
        }
        assert!(
            unsatisfied.is_empty(),
            "crates whose SPDX expression has no overlap with deny.toml allowlist: {unsatisfied:?}",
        );
    }

    fn parse_deny_allow_list(contents: &str) -> std::collections::BTreeSet<String> {
        use std::collections::BTreeSet;

        // Minimal TOML scanner targeted at `deny.toml`'s shape — finds the
        // `[licenses]` table's `allow` array and collects every double-quoted
        // SPDX identifier inside it, across a single-line or multi-line form.
        // A full TOML parser would be nicer but pulling one in as a dev-dep
        // just to read this shape feels disproportionate.
        let mut allow = BTreeSet::new();
        let mut in_licenses_section = false;
        let mut collecting_allow = false;
        for raw_line in contents.lines() {
            let line = strip_toml_comment(raw_line).trim();
            if let Some(section) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                in_licenses_section = section.trim() == "licenses";
                collecting_allow = false;
                continue;
            }
            if !in_licenses_section {
                continue;
            }
            let body = if collecting_allow {
                Some(line)
            } else if let Some(rest) = line.strip_prefix("allow") {
                let rest = rest.trim_start();
                let rest = rest.strip_prefix('=').map(str::trim_start).unwrap_or(rest);
                if let Some(after_open) = rest.strip_prefix('[') {
                    collecting_allow = true;
                    Some(after_open)
                } else {
                    None
                }
            } else {
                None
            };
            if let Some(body) = body {
                let (before_close, hit_close) = match body.find(']') {
                    Some(idx) => (&body[..idx], true),
                    None => (body, false),
                };
                extract_quoted_ids(before_close, &mut allow);
                if hit_close {
                    collecting_allow = false;
                }
            }
        }
        allow
    }

    fn strip_toml_comment(line: &str) -> &str {
        // Good enough: comments in deny.toml's allow section don't contain `"`.
        line.find('#').map_or(line, |idx| &line[..idx])
    }

    fn extract_quoted_ids(s: &str, out: &mut std::collections::BTreeSet<String>) {
        let mut rest = s;
        while let Some(start) = rest.find('"') {
            let after = &rest[start + 1..];
            if let Some(end) = after.find('"') {
                out.insert(after[..end].to_string());
                rest = &after[end + 1..];
            } else {
                break;
            }
        }
    }

    #[test]
    fn parses_deny_toml_allow_list_shape() {
        let toml = r#"
[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Zlib",
]
[bans]
multiple-versions = "allow"
"#;
        let allow = parse_deny_allow_list(toml);
        let expected: std::collections::BTreeSet<String> =
            ["Apache-2.0", "MIT", "Zlib"].into_iter().map(String::from).collect();
        assert_eq!(allow, expected);
    }

    #[test]
    fn parses_deny_toml_allow_list_inline() {
        let toml = r#"[licenses]
allow = ["MIT", "ISC"]
"#;
        let allow = parse_deny_allow_list(toml);
        let expected: std::collections::BTreeSet<String> = ["MIT", "ISC"].into_iter().map(String::from).collect();
        assert_eq!(allow, expected);
    }

    #[test]
    fn parse_deny_allow_list_ignores_other_sections() {
        let toml = r#"
[bans]
allow = ["not-a-license"]
[licenses]
allow = ["MIT"]
"#;
        let allow = parse_deny_allow_list(toml);
        assert!(!allow.contains("not-a-license"));
        assert!(allow.contains("MIT"));
    }
}
