//! Access to the third-party dependency manifest that `build.rs` embeds into
//! the binaries at compile time.
//!
//! The build script writes three files into `OUT_DIR`:
//!
//! * `third_party_licenses.json`      — uncompressed structured data; the
//!   release workflow copies this straight into the archive as
//!   `THIRD-PARTY-LICENSES.json`. Not embedded in the binary (~3 MB).
//! * `third_party_licenses.json.gz`   — zlib-compressed JSON; embedded here
//!   via `include_bytes!` and decompressed on demand by [`load`]. Keeps
//!   binary growth on the order of a few hundred KB.
//! * `third_party_licenses.txt`       — pre-rendered plain text, shipped as
//!   `THIRD-PARTY-LICENSES.txt` in the release archive. The runtime does not
//!   embed this; `super::render::render_all` can regenerate byte-identical
//!   output from a loaded [`Manifest`] whenever `gix licenses --all` or
//!   `ein licenses --all` is invoked.

use std::io;

use super::types::Manifest;

/// Zlib-compressed JSON manifest, embedded at compile time.
pub const JSON_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/third_party_licenses.json.gz"));

/// Decompress the embedded JSON into an owned UTF-8 string.
///
/// This is exposed so the `licenses --format json` subcommand can stream the
/// manifest verbatim without re-serialising a parsed `Manifest`.
pub fn json() -> io::Result<String> {
    let bytes = miniz_oxide::inflate::decompress_to_vec_zlib(JSON_GZ)
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, format!("inflate failed: {e:?}")))?;
    String::from_utf8(bytes).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("embedded manifest is not valid UTF-8: {e}"),
        )
    })
}

/// Parse the embedded manifest into a [`Manifest`].
///
/// Errors here are treated as fatal by the subcommands — they indicate a
/// build-script/runtime schema drift or a corrupted embedded blob, neither
/// of which the CLI can recover from usefully.
pub fn load() -> io::Result<Manifest> {
    let json_str = json()?;
    serde_json::from_str(&json_str).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("failed to parse embedded license manifest: {e}"),
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_blob_decompresses_to_utf8_json() {
        let text = json().expect("decompression and utf-8 check must succeed");
        assert!(!text.is_empty(), "decompressed JSON must be non-empty");
        assert!(
            text.trim_start().starts_with('{'),
            "decompressed output should be a JSON object"
        );
    }

    #[test]
    fn embedded_manifest_round_trips_through_serde() {
        let manifest = load().expect("embedded manifest must round-trip through serde");
        // Either the real manifest (many crates) or a stub (zero crates,
        // generated_at starting with "stub;"). Both are acceptable; anything
        // that fails to deserialise is not.
        assert!(!manifest.target_triple.is_empty() || manifest.generated_at.starts_with("stub"));
    }

    #[test]
    fn runtime_render_matches_archive_txt_byte_for_byte() {
        // The `THIRD-PARTY-LICENSES.txt` in release archives is generated by
        // `build.rs` via `render_all`. The binary regenerates the same bytes
        // at runtime from the embedded JSON via the very same function — so
        // `gix licenses --all` output must equal the archive file verbatim.
        let manifest = load().expect("load manifest");
        let mut rendered = Vec::new();
        super::super::render::render_all(&mut rendered, &manifest).expect("render_all");

        let txt_from_out_dir = std::fs::read(concat!(env!("OUT_DIR"), "/third_party_licenses.txt"))
            .expect("archive .txt must exist in OUT_DIR");

        assert_eq!(
            rendered,
            txt_from_out_dir,
            "runtime rendering drifted from build-time rendering (byte counts: runtime={}, build={})",
            rendered.len(),
            txt_from_out_dir.len(),
        );
    }

}
