name: setup-windows-arm-rustup

description: Set up Rustup for AMD64 Windows

runs:
  using: composite

  steps:
    - name: Install Rustup
      run: |
        if (Get-Command rustup -ErrorAction SilentlyContinue) {
          Write-Output '::warning:: The runner has rustup. Consider removing this step.'
        } else {
          $file = 'rustup-init.exe'
          $url = "https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/$file"
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL --output $file $url
          & ".\$file" --default-toolchain none -y
          Remove-Item $file
          Add-Content -Value "$Env:USERPROFILE\.cargo\bin" -Path $Env:GITHUB_PATH
        }
      shell: pwsh
