name: upgrade-git-for-windows

description: Upgrade Git for Windows to the latest stable release

inputs:
  arch:
    description: >
      Target architecture fragment of Git for Windows installer filename
      (should be `32-bit`, `64-bit`, or `arm64`)
    required: true

runs:
  using: composite

  steps:
    - name: Step that shall be removed  # FIXME: Remove this step after testing.
      run: |
        Write-Output '::notice:: This notice is for testing and shall be removed.'
      shell: pwsh
    - name: Report version/build of Git in this runner image
      run: git version --build-options
      shell: pwsh
    - name: Download and install latest stable Git for Windows release
      env:
        ARCH: ${{ inputs.arch }}
        GH_TOKEN: ${{ github.token }}
      run: |
        $workingDir = '~/git-dl'
        $repo = 'git-for-windows/git'
        $pattern = "Git-*-${Env:ARCH}.exe"
        $log = 'setup-log.txt'
        # Inno Setup args reference: https://jrsoftware.org/ishelp/index.php?topic=setupcmdline
        $arguments = @(
          '/VERYSILENT',
          '/SUPPRESSMSGBOXES',
          '/ALLUSERS',
          "/LOG=$log",
          '/NORESTART',
          '/CLOSEAPPLICATIONS',
          '/FORCECLOSEAPPLICATIONS'
        )

        mkdir $workingDir | Out-Null
        cd $workingDir
        gh release download --repo $repo --pattern $pattern
        $installer = Get-Item $pattern
        Start-Process -FilePath $installer -ArgumentList $arguments -NoNewWindow -Wait

        Get-Content -Path $log -Tail 50
      shell: pwsh
    - name: Report version/build of Git after upgrade
      run: git version --build-options
      shell: pwsh
